before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get install libsdl2-dev

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
