before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  
install:
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
